### ISSUE TITLE
Avklare kalenderkrav (modell)

### ISSUE THREAD

**Issue by ljodal** [cybrairai/internsystem#17]
Dagens kalendersystem er basert på to sider i en wiki. Det er ikke optimalt.

Jeg har egentlig bare sett for meg et par krav:
 * Lett å bruke
 * Mulig å integrere på forsiden (hvis ønskelig)
 * Evt. integrert i wikien

Så langt har jeg satt opp en modell med følgende informasjon:
 * Navn og beskrivelse
 * Om det er en intern hendelse
 * Om det er et utlån
 * Om det er et arrangement i Escape

Har også lagt inn støtte for å generere iCal-feeds

Innspill?

**Comment by henrist** [comment]
For å legge til: Det er også lagt inn felter for:
* Tid start
* Tid slutt
* Evt. om tid betyr hele dager (altså kun dato, ikke tid spesifisert)
* Om arrangementet er avlyst

Innspill:
* Hva med å ha en ansvarlig per arr? (Referanse mot core.User)
* På wikien kan man se historikk, bør vi ha en slags loggfunksjon her, så endringer i det minste logges tekstlig? Bør egentlig være et krav for å kunne holde seg oppdatert på endringer.
* Jeg tenker alle påloggede brukere skal kunne redigere kalenderen (hvis ting logges bør det i hvert fall ikke være noe problem)
* Hva med å kunne legge inn en lenke for arret? F.eks. for å lenke videre til et Facebook-arr

Hvordan skal vi håndtere arrangementer som man tidligere ikke har hatt dato for, men allikevel lagt under f.eks. en måned? Jeg tenker vel egentlig at det må planlegges utenom, f.eks. på en egen wikiside eller noe, og legges i kalenderen når dato faktisk er fastsatt.

**Comment by henrist** [comment]
Andre innspill:
* Må eksponere alle public events i åpen API som kan brukes av nye CYB-sia
* Integrasjon på wiki ser jeg ikke behov for, heller en lenke fra wikien som går til kalenderløsningen
* Bør vi kunne markere events som usikre, slik at de ikke dukker på public liste? (I stedet for at man ikke setter public, også glemmer man å sette det public senere når ting blir spikra)

**Comment by ljodal** [comment]
* En ansvarlig pr. arr. er jeg absolutt for. Regner med at du mener det skal være mulig å sette, og ikke bare være den som opprettet arrangementet?
* Historikk burde vi ha. Har Django noe innebygd eller må vi skrive noe selv?
* Hvem kan logge inn? Er det alle med UiO-konto eller bare interne? Jeg syns alle interne skal kunne redigere
* Lenker er greit, men det kan jo også legges i beskrivelsen?
* Public API burde vi absolutt ha. Må se på CORS for å kunne integrere på forsiden
* I forhold til usikre events er jeg litt skeptisk samtidig som at jeg ser fordel

**Comment by vegardli** [comment]
Er det ikke like lett å glemme å sette et arrangement som ikke lengre usikkert?

**Comment by matsasc** [comment]
Man kan jo legge til en eller annen form for purrefunksjon da. Mail x dager før arret skal være eller noe sånt for usikre arr eller noe sånt

**Comment by henrist** [comment]
@ljodal:
* Ansvarlige: Ja, sette hvem som helst som ansvarlige
* Historikk: Usikker. Vet Django har det på admin-sidene, kanskje noe som kan gjenbrukes, ikke vet jeg? Evt. overloade save-metoden og sjekke hva som har endret seg?
* Innlogging: Per i dag er det alle med UiO + hvem som helst som registrerer seg med weblogin. På sikt må dettte begrenses, men i dag ser jeg ikke det som problem. Vil i så fall være felles med andre prosjekter så ikke noe jeg synes vi skal tenke på nå.
* Lenker: Beskrivelse ja, men kan det være mer praktisk å kunne gjøre arrangement-teksten på f.eks. nettsiden til en lenke som går til en bestemt side? Alternativt må vi inn med egen syntaks/HTML for å støtte slikt, noe jeg synes vi skal unngå.

@vegardli:
* Usikre arr: Ja, det kan i og for seg også glemmes, men en vesentlig forskjell er at et arrangement KAN være både public/ikke-public uten at det er noe galt. Men et arr skal ikke være usikkert i evig tid, så sånn sett er det enklere å skille ut det som på et tidspunkt skal rettes

**Comment by henrist** [comment]
Avklaring: Bruke (teste ut) [django-revision](http://django-reversion.readthedocs.org/en/latest/index.html) for å håndtere endringshistorikk.
