### ISSUE TITLE
API-punkter for NFC-systemet

### ISSUE THREAD

**Issue by henrist** [cybrairai/internsystem#30]
Skisse vi jobber etter:

```
GET /api/nfc?card=123456 <-- kortnr til brukeren
GET /api/nfc?user=henrste <-- brukernavnet
POST /api/bong/henrste <-- bonger skal tilknyttes brukere
POST /api/coffee/124155 <-- id for kaffekortet, kaffekort må ikke kobles mot bruker
```

Når man søker opp med kort:
- Returner evt. kaffekort som eksisterer
- Returner evt. brukerinfo, inkl. evt. flere kaffekort

Når man søker opp med bruker:
- Returner evt. brukerinfo, inkl. evt. flere kaffekort

Tilordne kort en bruker: Dette ønsker vi brukeren selv skal gjøre via nettsia. Logge inn med UiO-bruker og legge inn kortnr sitt.

Registrere kaffekort: Dette bør være mulig via API-et. Kan f.eks. være hvis man POSTer til coffee-API-et.

Mulighet for modell:

```
`kaffekort` (kaffekortid, kortnr, saldo (cache))
`kaffekorttransaksjoner` (transid, kaffekortid, dato, bevegelse)
`user` utvides med bongsaldo (cache)
`bongtransaksjon` (transid, userid, dato, bevegelse)
`kort` (kortnr, userid)
```

Må også legge til mer info om hva som forårsaket transaksjoner

**Comment by henrist** [comment]
En god del er nå implementert, dog med andre adresser enn hva som er nevnt her. Kaffebonger ikke implementert enda.

**Comment by nicolaei** [comment]
Det er nå lagt opp til NFC systemet med #38! :D
