### ISSUE TITLE
Support different UID-lengths on NFC Cards

### ISSUE THREAD

**Issue by henrist** [cybrairai/internsystem#43]
Not all cards UID are 8 in length

And it is probably in hex, not [a-z0-9]

https://github.com/cybrairai/internsystem/blob/master/core/models.py#L103
(https://github.com/cybrairai/internsystem/blob/3813f8792afcd614b5b6203591255d10a8bade09/core/models.py#L103)

http://stackoverflow.com/questions/16080131/nfc-tags-unique-id

**Comment by nicolaei** [comment]
I'll fix it ASAP

**Comment by N0K0** [comment]
Seems like the shortest normal length is 4 bytes, and then just to some random sizes up to whatever, but its always Hex if read with a normal scanner, for example `^[a-f0-9]{4,}$` given that casing is ignored.
