### ISSUE TITLE
Endre navn på prosjektet

### ISSUE THREAD

**Issue by henrist** [cybrairai/internsystem#5]
Nå ligger prosjektet under http://internt.cyb.no/

Skal vi endre navn fra `okonomi` til f.eks. `internt`? Evt kanskje `internsystem`?

**Comment by ljodal** [comment]
Jeg stemmer for. Jeg stemmer også for at vi merger med shifty på et eller annet tidspunkt

**Comment by matsasc** [comment]
Jeg kan godt si meg enig i at internsystem er et bedre navn. I alle fall om man utvider funksjonaliteten ut over bare hva økonomigruppa driver med, som sigurd skriver, merger med shifty, får inn medlemsystem, tilgangsystem, internkort etc

**Comment by henrist** [comment]
Innspill @olivaq, @myrsnipe?

**Comment by myrsnipe** [comment]
Jeg sier meg enig at `internsystem ` er bedre. Angående shifty, her tror jeg det er en god ide å identifisere hvilke moduler/systemer/modeller som vil være felles for systemene og fokusere på de først, det er viktig at vi ikke blir avhengig av progresjon fra andre prosjekter.

**Comment by henrist** [comment]
Da har jeg renamet prosjektet til `internsystem`. Husk og oppdatere remotes. Kan enklest gjøres i `.git/config`-fila lokalt.
